local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:secret_access_key) %>
  region: us-west-2
  bucket: kevflix